### ISSUE TITLE
Level 2 task 7

### ISSUE THREAD

**Issue by panch8** [motoko-bootcamp/dao-adventure#1]
Hey Seb! whats up?
Listen, Is there any reason on why the removeMember function need to receive a argument of type principal? 

what about this approach?
```
public shared ({caller})func removeMember():async Result<(),Text>{
    switch(members.remove(caller)) {
      case(null) {
        #err("Caller is not a Member")
        };
      case(?val){#ok()}
    };

  }
```

**Comment by seb-icp** [comment]
No, there is no good reason. You're totally right. I will let him as it for the open because everyone needs to share the same interface for verification purposes 👍

**Comment by panch8** [comment]
Great! by the way, verification process went Ok either with or with out argument.

**Comment by panch8** [comment]
closing issue to clean the repo
