### ISSUE TITLE
Suggested Image Additions for Motoko Bootcamp [Level 1 ... Level 6]

### ISSUE THREAD

**Issue by bobekas** [motoko-bootcamp/dao-adventure#3]
### Level 1
![DALL·E 2023-11-22 13 05 41 - A completely text-free futuristic academy scene, emphasizing visual storytelling  The central area features a hologram with a DAO screen, sans any tex](https://github.com/motoko-bootcamp/dao-adventure/assets/14299408/a095486c-9b23-4852-a906-7e28605d36f9)
### Level 2
![DALL·E 2023-11-22 13 05 46 - An image capturing the dynamic and electric atmosphere of a futuristic academy, where students are deeply engaged in passionate conversations and coll](https://github.com/motoko-bootcamp/dao-adventure/assets/14299408/90df425b-e88b-43d3-9e8b-5897018e977e)
### Level 3
- Variant 1:
![DALL·E 2023-11-22 12 22 10 - Adjusting the image to feature a large, central coin that resembles a real-life metallic coin, not a cryptocurrency, with a fuel symbol embossed insid](https://github.com/motoko-bootcamp/dao-adventure/assets/14299408/1752cbe0-a189-4d63-8145-41937b777b70)
- Variant 2:
![DALL·E 2023-11-22 13 05 53 - An updated image of the futuristic academy's grand room, with a key change in the representation of tokens  Instead of a cryptocurrency-like design, t](https://github.com/motoko-bootcamp/dao-adventure/assets/14299408/f58f4d6d-2bc9-4c69-ac32-0f252b43296e)
### Level 4
![DALL·E 2023-11-22 13 06 02 - Reimagining the 'Collective Voice' concept in a futuristic academy with an artistic flair  In this version, the students and faculty gathered around t](https://github.com/motoko-bootcamp/dao-adventure/assets/14299408/98be0ff1-f30a-475d-a7c4-a778ea1d1fe8)
### Level 5
![DALL·E 2023-11-22 13 06 10 - An updated image showing a monitor in a contemporary workspace, but with a simpler design on the screen  The monitor now displays a single, iconic sym](https://github.com/motoko-bootcamp/dao-adventure/assets/14299408/01a94879-3b46-422c-b10d-42bbc349c669)
### Level 6
![DALL·E 2023-11-22 13 06 18 - A simplified celebratory image for reaching Level 6 in a DAO-course, focusing on 'Keep Building!', but without any text  The illustration includes a c](https://github.com/motoko-bootcamp/dao-adventure/assets/14299408/a8f97672-e630-40a4-b4de-87064c4a2c36)

**Comment by seb-icp** [comment]
Love it ❤️ 
Can you make a PR : https://www.youtube.com/watch?v=8A4TsoXJOs8 ?
